FROM voidlinux/voidlinux

RUN xbps-install -Syu && \
      xbps-install -Sy \
      bash \
      git \
      make

WORKDIR /work
COPY . .
RUN make && \
      xbps-install -Syu && \
      xbps-install -S \
      --repository=http://alpha.de.repo.voidlinux.org/current/nonfree \
      --repository=http://alpha.de.repo.voidlinux.org/current \
      -c /work/xbps-cachedir-x86_64 \
      $(grep -h '^[^#].' packages.base) \
      -y
