FROM base

ENV PACKAGES=packages.mklive
WORKDIR /work

COPY ${PACKAGES} .
RUN xbps-install -Syu && \
      xbps-install -S \
      --repository=http://alpha.de.repo.voidlinux.org/current/nonfree \
      --repository=http://alpha.de.repo.voidlinux.org/current \
      -c /work/xbps-cachedir-x86_64 \
      $(grep -h '^[^#].' ${PACKAGES}) \
      -y
